Algoritmo "semnome"
//Uma confecção produz X blusas de lã e para isto gasta uma certa
//quantidade de novelos. Faça um algoritmo para calcular quantos
//novelos de lã ela gasta por blusa.
Var
X,y,resultado:real
Inicio
Escreval("Digite a quantidade de novelos de lã: ")
leia(x)
Escreval("Digite a quantidade de blusas: ")
leia(y)
resultado<-x/y
Escreval("a quantidade de novelos de lã por blusas é: ",resultado)
Fimalgoritmo