Algoritmo "semnome"
//Alguns países medem temperaturas em graus Celsius, e outros em
//graus Fahrenheit. Faça um algoritmo para ler uma temperatura Celsius e
//imprimi-Ia em Fahrenheit (pesquise como fazer este tipo de conversão).
Var
Cel,fahr:real
Inicio
Escreval("Quantos graus celsius você queir converter para fahrenheit?: ")
leia(Cel)
Fahr<- 32+Cel*1.8
Escreval("Esta é a temperatura em Fahrenheit: ",Fahr)
Fimalgoritmo