Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2023
Var
// Seção de Declarações das variáveis 
x,y,z:real

Inicio
escreva("Raio:")
leia(x)
y<-(x^2)*3.14
escreva("Area:",y)



Fimalgoritmo